import type { RoleContext, RoleResult } from "../commands/router";
import type { GitHubModelsWorkflowClient } from "../llm/github-models";

export async function runResearch(
  input: RoleContext,
  llmClient: GitHubModelsWorkflowClient,
): Promise<RoleResult> {
  const repositoryContext =
    input.repositoryContext ?? "Repository context is not available for this research run.";

  const content = await llmClient.renderArtifact({
    title: "Research",
    summary: "Initial context gathering artifact generated by the research agent scaffold.",
    sections: [
      {
        heading: "Context",
        bullets: [
          "Task source was routed into the research step.",
          `Source channel: ${input.source}`,
          "Repository metadata was fetched from GitHub before generating this artifact.",
        ],
      },
      {
        heading: "Repository Snapshot",
        body: repositoryContext,
      },
      {
        heading: "Unknowns",
        bullets: [
          "The scaffold only captures a lightweight repository snapshot.",
          "Deeper code understanding still depends on richer repository indexing or search.",
        ],
      },
      {
        heading: "Assumptions",
        body: input.taskBody,
      },
    ],
  });

  return {
    kind: "artifact",
    fileName: "research.md",
    content,
    summary: "Research artifact scaffolded successfully.",
  };
}
