import type { RoleContext, RoleResult } from "../commands/router";
import type { GitHubModelsWorkflowClient } from "../llm/github-models";

export async function runResearch(
  input: RoleContext,
  llmClient: GitHubModelsWorkflowClient,
): Promise<RoleResult> {
  const content = await llmClient.renderArtifact({
    title: "Research",
    summary: "Initial context gathering artifact generated by the research agent scaffold.",
    sections: [
      {
        heading: "Context",
        bullets: [
          "Task source was routed into the research step.",
          "This scaffold does not yet fetch repository-wide context automatically.",
          `Source channel: ${input.source}`,
        ],
      },
      {
        heading: "Relevant Files",
        bullets: [
          "src/server.ts",
          "src/commands/router.ts",
          "src/roles/research.ts",
          "src/github/pr.ts",
        ],
      },
      {
        heading: "Unknowns",
        bullets: [
          "The exact repository files to inspect have not been resolved yet.",
          "Artifact persistence to GitHub is still a stub in this scaffold.",
        ],
      },
      {
        heading: "Assumptions",
        body: input.taskBody,
      },
    ],
  });

  return {
    kind: "artifact",
    fileName: "research.md",
    content,
    summary: "Research artifact scaffolded successfully.",
  };
}
